name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    container: gcr.io/k8s-staging-releng/releng-ci:latest
    timeout-minutes: 20
    steps:

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15'

      - name: Run verify
        run: make verify

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
